// Generated by scripts/gen-types.mjs from the live schema. Do not edit by hand.
// Re-run after any migration that changes a table.

export type Json = string | number | boolean | null | { [key: string]: Json } | Json[];

export type Database = {
  public: {
    Tables: {
      authorizations: {
        Row: {
          id: string;
          legacy_id: string | null;
          client_id: string;
          number: string;
          service_type: string;
          funding_source: string;
          total_hours: number | null;
          carried_used: number;
          rate_type: string;
          rate: number;
          start_date: string | null;
          end_date: string | null;
          status: string;
          requires_forms: string;
          note: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          legacy_id?: string | null;
          client_id: string;
          number?: string;
          service_type: string;
          funding_source?: string;
          total_hours?: number | null;
          carried_used?: number;
          rate_type: string;
          rate?: number;
          start_date?: string | null;
          end_date?: string | null;
          status?: string;
          requires_forms?: string;
          note?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          legacy_id?: string | null;
          client_id?: string;
          number?: string;
          service_type?: string;
          funding_source?: string;
          total_hours?: number | null;
          carried_used?: number;
          rate_type?: string;
          rate?: number;
          start_date?: string | null;
          end_date?: string | null;
          status?: string;
          requires_forms?: string;
          note?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      client_private: {
        Row: {
          client_id: string;
          dob: string | null;
          address: string;
          updated_at: string;
        };
        Insert: {
          client_id: string;
          dob?: string | null;
          address?: string;
          updated_at?: string;
        };
        Update: {
          client_id?: string;
          dob?: string | null;
          address?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      client_stage_history: {
        Row: {
          id: string;
          client_id: string;
          stage: string;
          at: string;
          staff_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          stage: string;
          at?: string;
          staff_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          stage?: string;
          at?: string;
          staff_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      clients: {
        Row: {
          id: string;
          legacy_id: string | null;
          client_no: number | null;
          ghl_id: string | null;
          name: string;
          agency_id: string;
          funding_source: string;
          caseload: string;
          unit: string;
          counselor_id: string | null;
          counselor_contact: string;
          referring_office: string;
          phone: string;
          email: string;
          gender: string;
          schedule: string;
          target_jobs: string;
          ce: boolean;
          wsa_tier: number | null;
          wsa_completed: string | null;
          wsa_submitted: string | null;
          wsa_paid: string | null;
          status: string;
          assigned_staff_id: string | null;
          stage: string;
          import_review: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          legacy_id?: string | null;
          client_no?: number | null;
          ghl_id?: string | null;
          name: string;
          agency_id?: string;
          funding_source?: string;
          caseload?: string;
          unit?: string;
          counselor_id?: string | null;
          counselor_contact?: string;
          referring_office?: string;
          phone?: string;
          email?: string;
          gender?: string;
          schedule?: string;
          target_jobs?: string;
          ce?: boolean;
          wsa_tier?: number | null;
          wsa_completed?: string | null;
          wsa_submitted?: string | null;
          wsa_paid?: string | null;
          status?: string;
          assigned_staff_id?: string | null;
          stage?: string;
          import_review?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          legacy_id?: string | null;
          client_no?: number | null;
          ghl_id?: string | null;
          name?: string;
          agency_id?: string;
          funding_source?: string;
          caseload?: string;
          unit?: string;
          counselor_id?: string | null;
          counselor_contact?: string;
          referring_office?: string;
          phone?: string;
          email?: string;
          gender?: string;
          schedule?: string;
          target_jobs?: string;
          ce?: boolean;
          wsa_tier?: number | null;
          wsa_completed?: string | null;
          wsa_submitted?: string | null;
          wsa_paid?: string | null;
          status?: string;
          assigned_staff_id?: string | null;
          stage?: string;
          import_review?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      completions: {
        Row: {
          id: string;
          legacy_id: string | null;
          auth_id: string;
          start_date: string | null;
          completion: string | null;
          notes: string;
          billed: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          legacy_id?: string | null;
          auth_id: string;
          start_date?: string | null;
          completion?: string | null;
          notes?: string;
          billed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          legacy_id?: string | null;
          auth_id?: string;
          start_date?: string | null;
          completion?: string | null;
          notes?: string;
          billed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      contact_log: {
        Row: {
          id: string;
          legacy_id: string | null;
          counselor_id: string | null;
          client_id: string | null;
          date: string;
          method: string;
          topic: string;
          outcome: string;
          follow_up: string | null;
          follow_up_done: boolean;
          staff_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          legacy_id?: string | null;
          counselor_id?: string | null;
          client_id?: string | null;
          date?: string;
          method?: string;
          topic?: string;
          outcome?: string;
          follow_up?: string | null;
          follow_up_done?: boolean;
          staff_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          legacy_id?: string | null;
          counselor_id?: string | null;
          client_id?: string | null;
          date?: string;
          method?: string;
          topic?: string;
          outcome?: string;
          follow_up?: string | null;
          follow_up_done?: boolean;
          staff_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      counselors: {
        Row: {
          id: string;
          legacy_id: string | null;
          name: string;
          agency: string;
          office: string | null;
          phone: string | null;
          fax: string | null;
          email: string | null;
          notes: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          legacy_id?: string | null;
          name: string;
          agency?: string;
          office?: string | null;
          phone?: string | null;
          fax?: string | null;
          email?: string | null;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          legacy_id?: string | null;
          name?: string;
          agency?: string;
          office?: string | null;
          phone?: string | null;
          fax?: string | null;
          email?: string | null;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      form_templates: {
        Row: {
          id: string;
          usor: string;
          name: string;
          services: string[];
          required_for_billing: boolean;
          monthly: boolean;
          incoming: boolean;
          sensitive: boolean;
          sort_order: number;
        };
        Insert: {
          id: string;
          usor: string;
          name: string;
          services?: string[];
          required_for_billing?: boolean;
          monthly?: boolean;
          incoming?: boolean;
          sensitive?: boolean;
          sort_order?: number;
        };
        Update: {
          id?: string;
          usor?: string;
          name?: string;
          services?: string[];
          required_for_billing?: boolean;
          monthly?: boolean;
          incoming?: boolean;
          sensitive?: boolean;
          sort_order?: number;
        };
        Relationships: [];
      };
      forms: {
        Row: {
          id: string;
          template_id: string;
          client_id: string;
          auth_id: string | null;
          month: string | null;
          status: string;
          data: Json;
          sensitive: boolean;
          created_by: string | null;
          created_by_name: string;
          created_at: string;
          completed_by: string | null;
          completed_by_name: string;
          completed_at: string | null;
          sent_at: string | null;
          sent_to: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          template_id: string;
          client_id: string;
          auth_id?: string | null;
          month?: string | null;
          status?: string;
          data?: Json;
          sensitive?: boolean;
          created_by?: string | null;
          created_by_name?: string;
          created_at?: string;
          completed_by?: string | null;
          completed_by_name?: string;
          completed_at?: string | null;
          sent_at?: string | null;
          sent_to?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          template_id?: string;
          client_id?: string;
          auth_id?: string | null;
          month?: string | null;
          status?: string;
          data?: Json;
          sensitive?: boolean;
          created_by?: string | null;
          created_by_name?: string;
          created_at?: string;
          completed_by?: string | null;
          completed_by_name?: string;
          completed_at?: string | null;
          sent_at?: string | null;
          sent_to?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      hours_requests: {
        Row: {
          id: string;
          auth_id: string | null;
          counselor_id: string | null;
          date: string;
          hours: number | null;
          reason: string;
          response: string;
          approved: number | null;
          approved_date: string | null;
          staff_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          auth_id?: string | null;
          counselor_id?: string | null;
          date?: string;
          hours?: number | null;
          reason?: string;
          response?: string;
          approved?: number | null;
          approved_date?: string | null;
          staff_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          auth_id?: string | null;
          counselor_id?: string | null;
          date?: string;
          hours?: number | null;
          reason?: string;
          response?: string;
          approved?: number | null;
          approved_date?: string | null;
          staff_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      intakes: {
        Row: {
          id: string;
          client_id: string;
          phone: string;
          email: string;
          address: string;
          emergency_name: string;
          emergency_phone: string;
          goals: string;
          availability: string;
          transportation: string;
          accommodations: string;
          consent_signed: boolean;
          submitted_at: string;
          updated_on: string | null;
          staff_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          phone?: string;
          email?: string;
          address?: string;
          emergency_name?: string;
          emergency_phone?: string;
          goals?: string;
          availability?: string;
          transportation?: string;
          accommodations?: string;
          consent_signed?: boolean;
          submitted_at?: string;
          updated_on?: string | null;
          staff_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          phone?: string;
          email?: string;
          address?: string;
          emergency_name?: string;
          emergency_phone?: string;
          goals?: string;
          availability?: string;
          transportation?: string;
          accommodations?: string;
          consent_signed?: boolean;
          submitted_at?: string;
          updated_on?: string | null;
          staff_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      invoices: {
        Row: {
          id: string;
          legacy_id: string | null;
          auth_id: string;
          number: string;
          date: string;
          amount: number;
          status: string;
          sent_date: string | null;
          paid_date: string | null;
          warrant: string;
          voucher: string;
          payee: string;
          service_type: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          legacy_id?: string | null;
          auth_id: string;
          number?: string;
          date?: string;
          amount: number;
          status?: string;
          sent_date?: string | null;
          paid_date?: string | null;
          warrant?: string;
          voucher?: string;
          payee?: string;
          service_type?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          legacy_id?: string | null;
          auth_id?: string;
          number?: string;
          date?: string;
          amount?: number;
          status?: string;
          sent_date?: string | null;
          paid_date?: string | null;
          warrant?: string;
          voucher?: string;
          payee?: string;
          service_type?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      notes: {
        Row: {
          id: string;
          legacy_id: string | null;
          client_id: string;
          staff_id: string | null;
          staff_name: string;
          text: string;
          type: string;
          at: string;
          ts: string;
          visible_roles: string[];
          created_at: string;
        };
        Insert: {
          id?: string;
          legacy_id?: string | null;
          client_id: string;
          staff_id?: string | null;
          staff_name?: string;
          text: string;
          type?: string;
          at?: string;
          ts?: string;
          visible_roles?: string[];
          created_at?: string;
        };
        Update: {
          id?: string;
          legacy_id?: string | null;
          client_id?: string;
          staff_id?: string | null;
          staff_name?: string;
          text?: string;
          type?: string;
          at?: string;
          ts?: string;
          visible_roles?: string[];
          created_at?: string;
        };
        Relationships: [];
      };
      offices: {
        Row: {
          name: string;
        };
        Insert: {
          name: string;
        };
        Update: {
          name?: string;
        };
        Relationships: [];
      };
      placements: {
        Row: {
          id: string;
          legacy_id: string | null;
          client_id: string;
          employer: string;
          title: string;
          start_date: string | null;
          wage: number | null;
          hours_week: number | null;
          check30: string | null;
          check60: string | null;
          check90: string | null;
          jp_submitted: string | null;
          jp_paid: string | null;
          notes: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          legacy_id?: string | null;
          client_id: string;
          employer?: string;
          title?: string;
          start_date?: string | null;
          wage?: number | null;
          hours_week?: number | null;
          check30?: string | null;
          check60?: string | null;
          check90?: string | null;
          jp_submitted?: string | null;
          jp_paid?: string | null;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          legacy_id?: string | null;
          client_id?: string;
          employer?: string;
          title?: string;
          start_date?: string | null;
          wage?: number | null;
          hours_week?: number | null;
          check30?: string | null;
          check60?: string | null;
          check90?: string | null;
          jp_submitted?: string | null;
          jp_paid?: string | null;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      rate_schedule: {
        Row: {
          id: string;
          funding_source: string;
          service: string;
          sub: string;
          fee: number;
          unit: string;
          effective_from: string | null;
          effective_to: string | null;
        };
        Insert: {
          id?: string;
          funding_source?: string;
          service: string;
          sub?: string;
          fee: number;
          unit: string;
          effective_from?: string | null;
          effective_to?: string | null;
        };
        Update: {
          id?: string;
          funding_source?: string;
          service?: string;
          sub?: string;
          fee?: number;
          unit?: string;
          effective_from?: string | null;
          effective_to?: string | null;
        };
        Relationships: [];
      };
      service_entries: {
        Row: {
          id: string;
          auth_id: string;
          date: string;
          hours: number;
          notes: string;
          non_billable: boolean;
          primary_code: string;
          secondary_code: string;
          staff_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          auth_id: string;
          date: string;
          hours: number;
          notes?: string;
          non_billable?: boolean;
          primary_code?: string;
          secondary_code?: string;
          staff_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          auth_id?: string;
          date?: string;
          hours?: number;
          notes?: string;
          non_billable?: boolean;
          primary_code?: string;
          secondary_code?: string;
          staff_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      sops: {
        Row: {
          id: string;
          legacy_id: string | null;
          title: string;
          roles: string[];
          body: string;
          screen: string | null;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          legacy_id?: string | null;
          title: string;
          roles?: string[];
          body?: string;
          screen?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          legacy_id?: string | null;
          title?: string;
          roles?: string[];
          body?: string;
          screen?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      staff: {
        Row: {
          id: string;
          user_id: string | null;
          legacy_id: string | null;
          name: string;
          email: string;
          phone: string | null;
          role: string;
          active: boolean;
          invited_at: string | null;
          accepted_at: string | null;
          deactivated_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          legacy_id?: string | null;
          name: string;
          email: string;
          phone?: string | null;
          role: string;
          active?: boolean;
          invited_at?: string | null;
          accepted_at?: string | null;
          deactivated_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          legacy_id?: string | null;
          name?: string;
          email?: string;
          phone?: string | null;
          role?: string;
          active?: boolean;
          invited_at?: string | null;
          accepted_at?: string | null;
          deactivated_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      tasks: {
        Row: {
          id: string;
          legacy_id: string | null;
          client_id: string | null;
          assigned_staff_id: string | null;
          title: string;
          due: string | null;
          status: string;
          done_at: string | null;
          created_by: string | null;
          system_generated: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          legacy_id?: string | null;
          client_id?: string | null;
          assigned_staff_id?: string | null;
          title: string;
          due?: string | null;
          status?: string;
          done_at?: string | null;
          created_by?: string | null;
          system_generated?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          legacy_id?: string | null;
          client_id?: string | null;
          assigned_staff_id?: string | null;
          title?: string;
          due?: string | null;
          status?: string;
          done_at?: string | null;
          created_by?: string | null;
          system_generated?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      can_see_restricted: {
        Args: { p_client_id: string };
        Returns: boolean;
      };
      current_staff_id: {
        Args: Record<string, never>;
        Returns: string;
      };
      current_staff_role: {
        Args: Record<string, never>;
        Returns: string;
      };
      is_active_staff: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      is_admin: {
        Args: Record<string, never>;
        Returns: boolean;
      };
    };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};

export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
export type Insert<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];
export type Update<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];
