// Generated by scripts/gen-types.mjs from the live schema. Do not edit by hand.
// Re-run after any migration that changes a table.

export type Json = string | number | boolean | null | { [key: string]: Json } | Json[];

export type Database = {
  public: {
    Tables: {
      attachments: {
        Row: {
          id: string;
          client_id: string;
          storage_path: string;
          filename: string;
          mime_type: string;
          size_bytes: number;
          category: string;
          restricted: boolean;
          note: string;
          form_id: string | null;
          auth_id: string | null;
          uploaded_by: string | null;
          uploaded_by_name: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          storage_path: string;
          filename: string;
          mime_type?: string;
          size_bytes?: number;
          category?: string;
          restricted?: boolean;
          note?: string;
          form_id?: string | null;
          auth_id?: string | null;
          uploaded_by?: string | null;
          uploaded_by_name?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          storage_path?: string;
          filename?: string;
          mime_type?: string;
          size_bytes?: number;
          category?: string;
          restricted?: boolean;
          note?: string;
          form_id?: string | null;
          auth_id?: string | null;
          uploaded_by?: string | null;
          uploaded_by_name?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      authorizations: {
        Row: {
          id: string;
          legacy_id: string | null;
          client_id: string;
          number: string;
          service_type: string;
          funding_source: string;
          total_hours: number | null;
          carried_used: number;
          rate_type: string;
          rate: number;
          start_date: string | null;
          end_date: string | null;
          status: string;
          requires_forms: string;
          note: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          legacy_id?: string | null;
          client_id: string;
          number?: string;
          service_type: string;
          funding_source?: string;
          total_hours?: number | null;
          carried_used?: number;
          rate_type: string;
          rate?: number;
          start_date?: string | null;
          end_date?: string | null;
          status?: string;
          requires_forms?: string;
          note?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          legacy_id?: string | null;
          client_id?: string;
          number?: string;
          service_type?: string;
          funding_source?: string;
          total_hours?: number | null;
          carried_used?: number;
          rate_type?: string;
          rate?: number;
          start_date?: string | null;
          end_date?: string | null;
          status?: string;
          requires_forms?: string;
          note?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      calendar_events: {
        Row: {
          id: string;
          client_id: string | null;
          staff_id: string;
          kind: string;
          title: string;
          starts_at: string;
          ends_at: string;
          location: string;
          note: string;
          origin: string;
          outlook_event_id: string | null;
          outlook_web_link: string | null;
          push_state: string;
          push_error: string;
          hours_prompt_answered_at: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          source_match_id: string | null;
          source_kind: string | null;
        };
        Insert: {
          id?: string;
          client_id?: string | null;
          staff_id: string;
          kind?: string;
          title: string;
          starts_at: string;
          ends_at: string;
          location?: string;
          note?: string;
          origin?: string;
          outlook_event_id?: string | null;
          outlook_web_link?: string | null;
          push_state?: string;
          push_error?: string;
          hours_prompt_answered_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          source_match_id?: string | null;
          source_kind?: string | null;
        };
        Update: {
          id?: string;
          client_id?: string | null;
          staff_id?: string;
          kind?: string;
          title?: string;
          starts_at?: string;
          ends_at?: string;
          location?: string;
          note?: string;
          origin?: string;
          outlook_event_id?: string | null;
          outlook_web_link?: string | null;
          push_state?: string;
          push_error?: string;
          hours_prompt_answered_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          source_match_id?: string | null;
          source_kind?: string | null;
        };
        Relationships: [];
      };
      checklist_tasks: {
        Row: {
          id: string;
          phase: string;
          label: string;
          detail: string;
          applies_to: string[] | null;
          auto_key: string | null;
          required: boolean;
          sort_order: number;
          active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          phase: string;
          label: string;
          detail?: string;
          applies_to?: string[] | null;
          auto_key?: string | null;
          required?: boolean;
          sort_order?: number;
          active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          phase?: string;
          label?: string;
          detail?: string;
          applies_to?: string[] | null;
          auto_key?: string | null;
          required?: boolean;
          sort_order?: number;
          active?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      client_private: {
        Row: {
          client_id: string;
          dob: string | null;
          address: string;
          updated_at: string;
        };
        Insert: {
          client_id: string;
          dob?: string | null;
          address?: string;
          updated_at?: string;
        };
        Update: {
          client_id?: string;
          dob?: string | null;
          address?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      client_stage_history: {
        Row: {
          id: string;
          client_id: string;
          stage: string;
          at: string;
          staff_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          stage: string;
          at?: string;
          staff_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          stage?: string;
          at?: string;
          staff_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      clients: {
        Row: {
          id: string;
          legacy_id: string | null;
          client_no: number | null;
          ghl_id: string | null;
          name: string;
          agency_id: string;
          funding_source: string;
          caseload: string;
          unit: string;
          counselor_id: string | null;
          counselor_contact: string;
          referring_office: string;
          phone: string;
          email: string;
          gender: string;
          schedule: string;
          target_jobs: string;
          ce: boolean;
          wsa_tier: number | null;
          wsa_completed: string | null;
          wsa_submitted: string | null;
          wsa_paid: string | null;
          status: string;
          assigned_staff_id: string | null;
          stage: string;
          import_review: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          legacy_id?: string | null;
          client_no?: number | null;
          ghl_id?: string | null;
          name: string;
          agency_id?: string;
          funding_source?: string;
          caseload?: string;
          unit?: string;
          counselor_id?: string | null;
          counselor_contact?: string;
          referring_office?: string;
          phone?: string;
          email?: string;
          gender?: string;
          schedule?: string;
          target_jobs?: string;
          ce?: boolean;
          wsa_tier?: number | null;
          wsa_completed?: string | null;
          wsa_submitted?: string | null;
          wsa_paid?: string | null;
          status?: string;
          assigned_staff_id?: string | null;
          stage?: string;
          import_review?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          legacy_id?: string | null;
          client_no?: number | null;
          ghl_id?: string | null;
          name?: string;
          agency_id?: string;
          funding_source?: string;
          caseload?: string;
          unit?: string;
          counselor_id?: string | null;
          counselor_contact?: string;
          referring_office?: string;
          phone?: string;
          email?: string;
          gender?: string;
          schedule?: string;
          target_jobs?: string;
          ce?: boolean;
          wsa_tier?: number | null;
          wsa_completed?: string | null;
          wsa_submitted?: string | null;
          wsa_paid?: string | null;
          status?: string;
          assigned_staff_id?: string | null;
          stage?: string;
          import_review?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      completions: {
        Row: {
          id: string;
          legacy_id: string | null;
          auth_id: string;
          start_date: string | null;
          completion: string | null;
          notes: string;
          billed: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          legacy_id?: string | null;
          auth_id: string;
          start_date?: string | null;
          completion?: string | null;
          notes?: string;
          billed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          legacy_id?: string | null;
          auth_id?: string;
          start_date?: string | null;
          completion?: string | null;
          notes?: string;
          billed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      contact_log: {
        Row: {
          id: string;
          legacy_id: string | null;
          counselor_id: string | null;
          client_id: string | null;
          date: string;
          method: string;
          topic: string;
          outcome: string;
          follow_up: string | null;
          follow_up_done: boolean;
          staff_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          legacy_id?: string | null;
          counselor_id?: string | null;
          client_id?: string | null;
          date?: string;
          method?: string;
          topic?: string;
          outcome?: string;
          follow_up?: string | null;
          follow_up_done?: boolean;
          staff_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          legacy_id?: string | null;
          counselor_id?: string | null;
          client_id?: string | null;
          date?: string;
          method?: string;
          topic?: string;
          outcome?: string;
          follow_up?: string | null;
          follow_up_done?: boolean;
          staff_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      contractor_payments: {
        Row: {
          id: string;
          staff_id: string;
          statement_id: string | null;
          paid_on: string;
          amount: number;
          method: string;
          reference: string;
          note: string;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          staff_id: string;
          statement_id?: string | null;
          paid_on: string;
          amount: number;
          method?: string;
          reference?: string;
          note?: string;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          staff_id?: string;
          statement_id?: string | null;
          paid_on?: string;
          amount?: number;
          method?: string;
          reference?: string;
          note?: string;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      contractor_profiles: {
        Row: {
          staff_id: string;
          legal_name: string;
          business_name: string;
          address_line1: string;
          address_line2: string;
          city: string;
          state: string;
          postal_code: string;
          tin_type: string | null;
          tin_encrypted: string | null;
          tin_last4: string | null;
          w9_received_on: string | null;
          notes: string;
          updated_at: string;
          tax_status: string;
          country: string;
          w8ben_received_on: string | null;
          w8ben_expires_on: string | null;
          e_delivery_consent_on: string | null;
        };
        Insert: {
          staff_id: string;
          legal_name?: string;
          business_name?: string;
          address_line1?: string;
          address_line2?: string;
          city?: string;
          state?: string;
          postal_code?: string;
          tin_type?: string | null;
          tin_encrypted?: string | null;
          tin_last4?: string | null;
          w9_received_on?: string | null;
          notes?: string;
          updated_at?: string;
          tax_status?: string;
          country?: string;
          w8ben_received_on?: string | null;
          w8ben_expires_on?: string | null;
          e_delivery_consent_on?: string | null;
        };
        Update: {
          staff_id?: string;
          legal_name?: string;
          business_name?: string;
          address_line1?: string;
          address_line2?: string;
          city?: string;
          state?: string;
          postal_code?: string;
          tin_type?: string | null;
          tin_encrypted?: string | null;
          tin_last4?: string | null;
          w9_received_on?: string | null;
          notes?: string;
          updated_at?: string;
          tax_status?: string;
          country?: string;
          w8ben_received_on?: string | null;
          w8ben_expires_on?: string | null;
          e_delivery_consent_on?: string | null;
        };
        Relationships: [];
      };
      contractor_statements: {
        Row: {
          id: string;
          staff_id: string;
          period_start: string;
          period_end: string;
          status: string;
          submitted_at: string | null;
          decided_at: string | null;
          decided_by: string | null;
          return_note: string;
          created_at: string;
          updated_at: string;
          adjustment: number;
          adjustment_note: string;
          approved_hours: number | null;
          approved_amount: number | null;
        };
        Insert: {
          id?: string;
          staff_id: string;
          period_start: string;
          period_end: string;
          status?: string;
          submitted_at?: string | null;
          decided_at?: string | null;
          decided_by?: string | null;
          return_note?: string;
          created_at?: string;
          updated_at?: string;
          adjustment?: number;
          adjustment_note?: string;
          approved_hours?: number | null;
          approved_amount?: number | null;
        };
        Update: {
          id?: string;
          staff_id?: string;
          period_start?: string;
          period_end?: string;
          status?: string;
          submitted_at?: string | null;
          decided_at?: string | null;
          decided_by?: string | null;
          return_note?: string;
          created_at?: string;
          updated_at?: string;
          adjustment?: number;
          adjustment_note?: string;
          approved_hours?: number | null;
          approved_amount?: number | null;
        };
        Relationships: [];
      };
      counselors: {
        Row: {
          id: string;
          legacy_id: string | null;
          name: string;
          agency: string;
          office: string | null;
          phone: string | null;
          fax: string | null;
          email: string | null;
          notes: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          legacy_id?: string | null;
          name: string;
          agency?: string;
          office?: string | null;
          phone?: string | null;
          fax?: string | null;
          email?: string | null;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          legacy_id?: string | null;
          name?: string;
          agency?: string;
          office?: string | null;
          phone?: string | null;
          fax?: string | null;
          email?: string | null;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      employers: {
        Row: {
          id: string;
          name: string;
          industry: string;
          address: string;
          contact_name: string;
          contact_phone: string;
          contact_email: string;
          notes: string;
          relationship_status: string;
          hiring_pattern: string;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          industry?: string;
          address?: string;
          contact_name?: string;
          contact_phone?: string;
          contact_email?: string;
          notes?: string;
          relationship_status?: string;
          hiring_pattern?: string;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          industry?: string;
          address?: string;
          contact_name?: string;
          contact_phone?: string;
          contact_email?: string;
          notes?: string;
          relationship_status?: string;
          hiring_pattern?: string;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      form_1099_recipients: {
        Row: {
          id: string;
          run_id: string;
          staff_id: string;
          legal_name: string;
          business_name: string;
          address_snapshot: string;
          tin_type: string | null;
          tin_last4: string | null;
          nonemployee_comp: number;
          corrected: boolean;
          corrects_id: string | null;
          delivered_on: string | null;
          delivery_method: string | null;
          consent_recorded: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          run_id: string;
          staff_id: string;
          legal_name: string;
          business_name?: string;
          address_snapshot?: string;
          tin_type?: string | null;
          tin_last4?: string | null;
          nonemployee_comp: number;
          corrected?: boolean;
          corrects_id?: string | null;
          delivered_on?: string | null;
          delivery_method?: string | null;
          consent_recorded?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          run_id?: string;
          staff_id?: string;
          legal_name?: string;
          business_name?: string;
          address_snapshot?: string;
          tin_type?: string | null;
          tin_last4?: string | null;
          nonemployee_comp?: number;
          corrected?: boolean;
          corrects_id?: string | null;
          delivered_on?: string | null;
          delivery_method?: string | null;
          consent_recorded?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      form_1099_runs: {
        Row: {
          id: string;
          year: number;
          threshold: number;
          state_copy: boolean;
          generated_at: string;
          generated_by: string | null;
          filed_on: string | null;
          iris_receipt: string;
          notes: string;
        };
        Insert: {
          id?: string;
          year: number;
          threshold: number;
          state_copy?: boolean;
          generated_at?: string;
          generated_by?: string | null;
          filed_on?: string | null;
          iris_receipt?: string;
          notes?: string;
        };
        Update: {
          id?: string;
          year?: number;
          threshold?: number;
          state_copy?: boolean;
          generated_at?: string;
          generated_by?: string | null;
          filed_on?: string | null;
          iris_receipt?: string;
          notes?: string;
        };
        Relationships: [];
      };
      form_templates: {
        Row: {
          id: string;
          usor: string;
          name: string;
          services: string[];
          required_for_billing: boolean;
          monthly: boolean;
          incoming: boolean;
          sensitive: boolean;
          sort_order: number;
        };
        Insert: {
          id: string;
          usor: string;
          name: string;
          services?: string[];
          required_for_billing?: boolean;
          monthly?: boolean;
          incoming?: boolean;
          sensitive?: boolean;
          sort_order?: number;
        };
        Update: {
          id?: string;
          usor?: string;
          name?: string;
          services?: string[];
          required_for_billing?: boolean;
          monthly?: boolean;
          incoming?: boolean;
          sensitive?: boolean;
          sort_order?: number;
        };
        Relationships: [];
      };
      forms: {
        Row: {
          id: string;
          template_id: string;
          client_id: string;
          auth_id: string | null;
          month: string | null;
          status: string;
          data: Json;
          sensitive: boolean;
          created_by: string | null;
          created_by_name: string;
          created_at: string;
          completed_by: string | null;
          completed_by_name: string;
          completed_at: string | null;
          sent_at: string | null;
          sent_to: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          template_id: string;
          client_id: string;
          auth_id?: string | null;
          month?: string | null;
          status?: string;
          data?: Json;
          sensitive?: boolean;
          created_by?: string | null;
          created_by_name?: string;
          created_at?: string;
          completed_by?: string | null;
          completed_by_name?: string;
          completed_at?: string | null;
          sent_at?: string | null;
          sent_to?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          template_id?: string;
          client_id?: string;
          auth_id?: string | null;
          month?: string | null;
          status?: string;
          data?: Json;
          sensitive?: boolean;
          created_by?: string | null;
          created_by_name?: string;
          created_at?: string;
          completed_by?: string | null;
          completed_by_name?: string;
          completed_at?: string | null;
          sent_at?: string | null;
          sent_to?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      hours_requests: {
        Row: {
          id: string;
          auth_id: string | null;
          counselor_id: string | null;
          date: string;
          hours: number | null;
          reason: string;
          response: string;
          approved: number | null;
          approved_date: string | null;
          staff_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          auth_id?: string | null;
          counselor_id?: string | null;
          date?: string;
          hours?: number | null;
          reason?: string;
          response?: string;
          approved?: number | null;
          approved_date?: string | null;
          staff_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          auth_id?: string | null;
          counselor_id?: string | null;
          date?: string;
          hours?: number | null;
          reason?: string;
          response?: string;
          approved?: number | null;
          approved_date?: string | null;
          staff_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      intakes: {
        Row: {
          id: string;
          client_id: string;
          phone: string;
          email: string;
          address: string;
          emergency_name: string;
          emergency_phone: string;
          goals: string;
          availability: string;
          transportation: string;
          accommodations: string;
          consent_signed: boolean;
          submitted_at: string;
          updated_on: string | null;
          staff_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          phone?: string;
          email?: string;
          address?: string;
          emergency_name?: string;
          emergency_phone?: string;
          goals?: string;
          availability?: string;
          transportation?: string;
          accommodations?: string;
          consent_signed?: boolean;
          submitted_at?: string;
          updated_on?: string | null;
          staff_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          phone?: string;
          email?: string;
          address?: string;
          emergency_name?: string;
          emergency_phone?: string;
          goals?: string;
          availability?: string;
          transportation?: string;
          accommodations?: string;
          consent_signed?: boolean;
          submitted_at?: string;
          updated_on?: string | null;
          staff_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      invoices: {
        Row: {
          id: string;
          legacy_id: string | null;
          auth_id: string;
          number: string;
          date: string;
          amount: number;
          status: string;
          sent_date: string | null;
          paid_date: string | null;
          warrant: string;
          voucher: string;
          payee: string;
          service_type: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          legacy_id?: string | null;
          auth_id: string;
          number?: string;
          date?: string;
          amount: number;
          status?: string;
          sent_date?: string | null;
          paid_date?: string | null;
          warrant?: string;
          voucher?: string;
          payee?: string;
          service_type?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          legacy_id?: string | null;
          auth_id?: string;
          number?: string;
          date?: string;
          amount?: number;
          status?: string;
          sent_date?: string | null;
          paid_date?: string | null;
          warrant?: string;
          voucher?: string;
          payee?: string;
          service_type?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      job_leads: {
        Row: {
          id: string;
          employer_id: string;
          title: string;
          wage_range: string;
          hours_week: string;
          shift: string;
          requirements: string;
          source: string;
          posted_date: string | null;
          status: string;
          owner_staff_id: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          location: string;
        };
        Insert: {
          id?: string;
          employer_id: string;
          title: string;
          wage_range?: string;
          hours_week?: string;
          shift?: string;
          requirements?: string;
          source?: string;
          posted_date?: string | null;
          status?: string;
          owner_staff_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          location?: string;
        };
        Update: {
          id?: string;
          employer_id?: string;
          title?: string;
          wage_range?: string;
          hours_week?: string;
          shift?: string;
          requirements?: string;
          source?: string;
          posted_date?: string | null;
          status?: string;
          owner_staff_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          location?: string;
        };
        Relationships: [];
      };
      lead_matches: {
        Row: {
          id: string;
          lead_id: string;
          client_id: string;
          status: string;
          applied_on: string | null;
          interview_on: string | null;
          decided_on: string | null;
          notes: string;
          placement_id: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          follow_up_on: string | null;
          outcome: string;
        };
        Insert: {
          id?: string;
          lead_id: string;
          client_id: string;
          status?: string;
          applied_on?: string | null;
          interview_on?: string | null;
          decided_on?: string | null;
          notes?: string;
          placement_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          follow_up_on?: string | null;
          outcome?: string;
        };
        Update: {
          id?: string;
          lead_id?: string;
          client_id?: string;
          status?: string;
          applied_on?: string | null;
          interview_on?: string | null;
          decided_on?: string | null;
          notes?: string;
          placement_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          follow_up_on?: string | null;
          outcome?: string;
        };
        Relationships: [];
      };
      mail_exclusions: {
        Row: {
          conversation_id: string;
          excluded_by: string | null;
          excluded_at: string;
          reason: string;
        };
        Insert: {
          conversation_id: string;
          excluded_by?: string | null;
          excluded_at?: string;
          reason?: string;
        };
        Update: {
          conversation_id?: string;
          excluded_by?: string | null;
          excluded_at?: string;
          reason?: string;
        };
        Relationships: [];
      };
      mail_log: {
        Row: {
          id: string;
          staff_id: string | null;
          client_id: string | null;
          counselor_id: string | null;
          graph_message_id: string;
          conversation_id: string;
          subject: string;
          sent_at: string;
          direction: string;
          counterpart_email: string;
          web_link: string;
          created_at: string;
          mailbox_address: string;
          mailbox_key: string | null;
        };
        Insert: {
          id?: string;
          staff_id?: string | null;
          client_id?: string | null;
          counselor_id?: string | null;
          graph_message_id: string;
          conversation_id?: string;
          subject?: string;
          sent_at: string;
          direction: string;
          counterpart_email: string;
          web_link?: string;
          created_at?: string;
          mailbox_address?: string;
          mailbox_key?: string | null;
        };
        Update: {
          id?: string;
          staff_id?: string | null;
          client_id?: string | null;
          counselor_id?: string | null;
          graph_message_id?: string;
          conversation_id?: string;
          subject?: string;
          sent_at?: string;
          direction?: string;
          counterpart_email?: string;
          web_link?: string;
          created_at?: string;
          mailbox_address?: string;
          mailbox_key?: string | null;
        };
        Relationships: [];
      };
      microsoft_connections: {
        Row: {
          staff_id: string;
          microsoft_user_id: string;
          microsoft_email: string;
          display_name: string;
          scopes: string;
          access_encrypted: string | null;
          refresh_encrypted: string | null;
          access_expires_at: string | null;
          connected_at: string;
          last_refreshed_at: string | null;
          last_error: string;
          updated_at: string;
        };
        Insert: {
          staff_id: string;
          microsoft_user_id: string;
          microsoft_email?: string;
          display_name?: string;
          scopes?: string;
          access_encrypted?: string | null;
          refresh_encrypted?: string | null;
          access_expires_at?: string | null;
          connected_at?: string;
          last_refreshed_at?: string | null;
          last_error?: string;
          updated_at?: string;
        };
        Update: {
          staff_id?: string;
          microsoft_user_id?: string;
          microsoft_email?: string;
          display_name?: string;
          scopes?: string;
          access_encrypted?: string | null;
          refresh_encrypted?: string | null;
          access_expires_at?: string | null;
          connected_at?: string;
          last_refreshed_at?: string | null;
          last_error?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      microsoft_sync_state: {
        Row: {
          staff_id: string;
          last_run_at: string | null;
          last_mail_sync_at: string | null;
          last_calendar_sync_at: string | null;
          mail_logged: number;
          events_pulled: number;
          last_error: string;
          updated_at: string;
        };
        Insert: {
          staff_id: string;
          last_run_at?: string | null;
          last_mail_sync_at?: string | null;
          last_calendar_sync_at?: string | null;
          mail_logged?: number;
          events_pulled?: number;
          last_error?: string;
          updated_at?: string;
        };
        Update: {
          staff_id?: string;
          last_run_at?: string | null;
          last_mail_sync_at?: string | null;
          last_calendar_sync_at?: string | null;
          mail_logged?: number;
          events_pulled?: number;
          last_error?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      notes: {
        Row: {
          id: string;
          legacy_id: string | null;
          client_id: string;
          staff_id: string | null;
          staff_name: string;
          text: string;
          type: string;
          at: string;
          ts: string;
          visible_roles: string[];
          created_at: string;
        };
        Insert: {
          id?: string;
          legacy_id?: string | null;
          client_id: string;
          staff_id?: string | null;
          staff_name?: string;
          text: string;
          type?: string;
          at?: string;
          ts?: string;
          visible_roles?: string[];
          created_at?: string;
        };
        Update: {
          id?: string;
          legacy_id?: string | null;
          client_id?: string;
          staff_id?: string | null;
          staff_name?: string;
          text?: string;
          type?: string;
          at?: string;
          ts?: string;
          visible_roles?: string[];
          created_at?: string;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          dedupe_key: string;
          kind: string;
          level: string;
          text: string;
          roles: string[];
          href: string | null;
          client_id: string | null;
          staff_id: string | null;
          created_at: string;
          resolved_at: string | null;
          emailed_at: string | null;
        };
        Insert: {
          id?: string;
          dedupe_key: string;
          kind: string;
          level: string;
          text: string;
          roles: string[];
          href?: string | null;
          client_id?: string | null;
          staff_id?: string | null;
          created_at?: string;
          resolved_at?: string | null;
          emailed_at?: string | null;
        };
        Update: {
          id?: string;
          dedupe_key?: string;
          kind?: string;
          level?: string;
          text?: string;
          roles?: string[];
          href?: string | null;
          client_id?: string | null;
          staff_id?: string | null;
          created_at?: string;
          resolved_at?: string | null;
          emailed_at?: string | null;
        };
        Relationships: [];
      };
      offices: {
        Row: {
          name: string;
        };
        Insert: {
          name: string;
        };
        Update: {
          name?: string;
        };
        Relationships: [];
      };
      org_settings: {
        Row: {
          id: boolean;
          pay_period: string;
          period_anchor: string;
          updated_at: string;
          employer_legal_name: string;
          employer_address: string;
          employer_ein: string;
        };
        Insert: {
          id?: boolean;
          pay_period?: string;
          period_anchor?: string;
          updated_at?: string;
          employer_legal_name?: string;
          employer_address?: string;
          employer_ein?: string;
        };
        Update: {
          id?: boolean;
          pay_period?: string;
          period_anchor?: string;
          updated_at?: string;
          employer_legal_name?: string;
          employer_address?: string;
          employer_ein?: string;
        };
        Relationships: [];
      };
      placements: {
        Row: {
          id: string;
          legacy_id: string | null;
          client_id: string;
          employer: string;
          title: string;
          start_date: string | null;
          wage: number | null;
          hours_week: number | null;
          check30: string | null;
          check60: string | null;
          check90: string | null;
          jp_submitted: string | null;
          jp_paid: string | null;
          notes: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          legacy_id?: string | null;
          client_id: string;
          employer?: string;
          title?: string;
          start_date?: string | null;
          wage?: number | null;
          hours_week?: number | null;
          check30?: string | null;
          check60?: string | null;
          check90?: string | null;
          jp_submitted?: string | null;
          jp_paid?: string | null;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          legacy_id?: string | null;
          client_id?: string;
          employer?: string;
          title?: string;
          start_date?: string | null;
          wage?: number | null;
          hours_week?: number | null;
          check30?: string | null;
          check60?: string | null;
          check90?: string | null;
          jp_submitted?: string | null;
          jp_paid?: string | null;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      rate_schedule: {
        Row: {
          id: string;
          funding_source: string;
          service: string;
          sub: string;
          fee: number;
          unit: string;
          effective_from: string | null;
          effective_to: string | null;
        };
        Insert: {
          id?: string;
          funding_source?: string;
          service: string;
          sub?: string;
          fee: number;
          unit: string;
          effective_from?: string | null;
          effective_to?: string | null;
        };
        Update: {
          id?: string;
          funding_source?: string;
          service?: string;
          sub?: string;
          fee?: number;
          unit?: string;
          effective_from?: string | null;
          effective_to?: string | null;
        };
        Relationships: [];
      };
      saved_views: {
        Row: {
          id: string;
          screen: string;
          name: string;
          owner_staff_id: string | null;
          params: Json;
          sort_order: number;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          screen: string;
          name: string;
          owner_staff_id?: string | null;
          params?: Json;
          sort_order?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          screen?: string;
          name?: string;
          owner_staff_id?: string | null;
          params?: Json;
          sort_order?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      service_entries: {
        Row: {
          id: string;
          auth_id: string;
          date: string;
          hours: number;
          notes: string;
          non_billable: boolean;
          primary_code: string;
          secondary_code: string;
          staff_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          auth_id: string;
          date: string;
          hours: number;
          notes?: string;
          non_billable?: boolean;
          primary_code?: string;
          secondary_code?: string;
          staff_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          auth_id?: string;
          date?: string;
          hours?: number;
          notes?: string;
          non_billable?: boolean;
          primary_code?: string;
          secondary_code?: string;
          staff_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      shared_mailboxes: {
        Row: {
          address: string;
          label: string;
          connected_by: string | null;
          active: boolean;
          last_mail_sync_at: string | null;
          last_run_at: string | null;
          mail_logged: number;
          last_error: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          address: string;
          label?: string;
          connected_by?: string | null;
          active?: boolean;
          last_mail_sync_at?: string | null;
          last_run_at?: string | null;
          mail_logged?: number;
          last_error?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          address?: string;
          label?: string;
          connected_by?: string | null;
          active?: boolean;
          last_mail_sync_at?: string | null;
          last_run_at?: string | null;
          mail_logged?: number;
          last_error?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      sops: {
        Row: {
          id: string;
          legacy_id: string | null;
          title: string;
          roles: string[];
          body: string;
          screen: string | null;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          legacy_id?: string | null;
          title: string;
          roles?: string[];
          body?: string;
          screen?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          legacy_id?: string | null;
          title?: string;
          roles?: string[];
          body?: string;
          screen?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      staff: {
        Row: {
          id: string;
          user_id: string | null;
          legacy_id: string | null;
          name: string;
          email: string | null;
          phone: string | null;
          role: string;
          active: boolean;
          invited_at: string | null;
          accepted_at: string | null;
          deactivated_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          legacy_id?: string | null;
          name: string;
          email?: string | null;
          phone?: string | null;
          role: string;
          active?: boolean;
          invited_at?: string | null;
          accepted_at?: string | null;
          deactivated_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          legacy_id?: string | null;
          name?: string;
          email?: string | null;
          phone?: string | null;
          role?: string;
          active?: boolean;
          invited_at?: string | null;
          accepted_at?: string | null;
          deactivated_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      staff_checklist_items: {
        Row: {
          staff_id: string;
          task_id: string;
          done_on: string | null;
          done_by: string | null;
          note: string;
          updated_at: string;
        };
        Insert: {
          staff_id: string;
          task_id: string;
          done_on?: string | null;
          done_by?: string | null;
          note?: string;
          updated_at?: string;
        };
        Update: {
          staff_id?: string;
          task_id?: string;
          done_on?: string | null;
          done_by?: string | null;
          note?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      staff_employment: {
        Row: {
          staff_id: string;
          employment_type: string;
          started_on: string | null;
          notes: string;
          updated_at: string;
        };
        Insert: {
          staff_id: string;
          employment_type?: string;
          started_on?: string | null;
          notes?: string;
          updated_at?: string;
        };
        Update: {
          staff_id?: string;
          employment_type?: string;
          started_on?: string | null;
          notes?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      staff_files: {
        Row: {
          id: string;
          staff_id: string;
          storage_path: string;
          filename: string;
          mime_type: string;
          size_bytes: number;
          category: string;
          note: string;
          uploaded_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          staff_id: string;
          storage_path: string;
          filename: string;
          mime_type?: string;
          size_bytes?: number;
          category?: string;
          note?: string;
          uploaded_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          staff_id?: string;
          storage_path?: string;
          filename?: string;
          mime_type?: string;
          size_bytes?: number;
          category?: string;
          note?: string;
          uploaded_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      staff_pay: {
        Row: {
          id: string;
          staff_id: string;
          pay_rate: number;
          rate_unit: string;
          effective_from: string;
          note: string;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          staff_id: string;
          pay_rate: number;
          rate_unit?: string;
          effective_from?: string;
          note?: string;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          staff_id?: string;
          pay_rate?: number;
          rate_unit?: string;
          effective_from?: string;
          note?: string;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      staff_prefs: {
        Row: {
          staff_id: string;
          key: string;
          value: Json;
          updated_at: string;
        };
        Insert: {
          staff_id: string;
          key: string;
          value: Json;
          updated_at?: string;
        };
        Update: {
          staff_id?: string;
          key?: string;
          value?: Json;
          updated_at?: string;
        };
        Relationships: [];
      };
      tasks: {
        Row: {
          id: string;
          legacy_id: string | null;
          client_id: string | null;
          assigned_staff_id: string | null;
          title: string;
          due: string | null;
          status: string;
          done_at: string | null;
          created_by: string | null;
          system_generated: boolean;
          created_at: string;
          updated_at: string;
          source_match_id: string | null;
          source_kind: string | null;
        };
        Insert: {
          id?: string;
          legacy_id?: string | null;
          client_id?: string | null;
          assigned_staff_id?: string | null;
          title: string;
          due?: string | null;
          status?: string;
          done_at?: string | null;
          created_by?: string | null;
          system_generated?: boolean;
          created_at?: string;
          updated_at?: string;
          source_match_id?: string | null;
          source_kind?: string | null;
        };
        Update: {
          id?: string;
          legacy_id?: string | null;
          client_id?: string | null;
          assigned_staff_id?: string | null;
          title?: string;
          due?: string | null;
          status?: string;
          done_at?: string | null;
          created_by?: string | null;
          system_generated?: boolean;
          created_at?: string;
          updated_at?: string;
          source_match_id?: string | null;
          source_kind?: string | null;
        };
        Relationships: [];
      };
      tax_form_submissions: {
        Row: {
          id: string;
          staff_id: string;
          form_type: string;
          status: string;
          data: Json;
          sensitive_encrypted: string | null;
          tin_last4: string | null;
          signed_at: string | null;
          signer_name: string | null;
          signer_ip: string | null;
          pdf_path: string | null;
          pdf_sha256: string | null;
          staff_file_id: string | null;
          supersedes_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          staff_id: string;
          form_type: string;
          status?: string;
          data?: Json;
          sensitive_encrypted?: string | null;
          tin_last4?: string | null;
          signed_at?: string | null;
          signer_name?: string | null;
          signer_ip?: string | null;
          pdf_path?: string | null;
          pdf_sha256?: string | null;
          staff_file_id?: string | null;
          supersedes_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          staff_id?: string;
          form_type?: string;
          status?: string;
          data?: Json;
          sensitive_encrypted?: string | null;
          tin_last4?: string | null;
          signed_at?: string | null;
          signer_name?: string | null;
          signer_ip?: string | null;
          pdf_path?: string | null;
          pdf_sha256?: string | null;
          staff_file_id?: string | null;
          supersedes_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      tax_years: {
        Row: {
          year: number;
          federal_threshold: number | null;
          utah_state_copy: boolean;
          confirmed_by: string | null;
          confirmed_on: string | null;
          notes: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          year: number;
          federal_threshold?: number | null;
          utah_state_copy?: boolean;
          confirmed_by?: string | null;
          confirmed_on?: string | null;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          year?: number;
          federal_threshold?: number | null;
          utah_state_copy?: boolean;
          confirmed_by?: string | null;
          confirmed_on?: string | null;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      tour_hints: {
        Row: {
          key: string;
          screen: string;
          title: string;
          body: string;
          roles: string[] | null;
          sort_order: number;
          active: boolean;
          created_at: string;
        };
        Insert: {
          key: string;
          screen: string;
          title: string;
          body: string;
          roles?: string[] | null;
          sort_order?: number;
          active?: boolean;
          created_at?: string;
        };
        Update: {
          key?: string;
          screen?: string;
          title?: string;
          body?: string;
          roles?: string[] | null;
          sort_order?: number;
          active?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      work_session_timers: {
        Row: {
          staff_id: string;
          started_at: string;
          note: string;
          client_id: string | null;
          created_at: string;
        };
        Insert: {
          staff_id: string;
          started_at?: string;
          note?: string;
          client_id?: string | null;
          created_at?: string;
        };
        Update: {
          staff_id?: string;
          started_at?: string;
          note?: string;
          client_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      work_sessions: {
        Row: {
          id: string;
          staff_id: string;
          worked_on: string;
          hours: number;
          description: string;
          client_id: string | null;
          statement_id: string | null;
          corrects_id: string | null;
          correction_reason: string;
          voided: boolean;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          staff_id: string;
          worked_on: string;
          hours: number;
          description?: string;
          client_id?: string | null;
          statement_id?: string | null;
          corrects_id?: string | null;
          correction_reason?: string;
          voided?: boolean;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          staff_id?: string;
          worked_on?: string;
          hours?: number;
          description?: string;
          client_id?: string | null;
          statement_id?: string | null;
          corrects_id?: string | null;
          correction_reason?: string;
          voided?: boolean;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      authorization_economics: {
        Row: {
          auth_id: string | null;
          client_id: string | null;
          auth_number: string | null;
          service_type: string | null;
          funding_source: string | null;
          status: string | null;
          rate_type: string | null;
          rate: number | null;
          total_hours: number | null;
          start_date: string | null;
          end_date: string | null;
          hours_used: number | null;
          hours_left: number | null;
          first_entry_on: string | null;
          last_entry_on: string | null;
          entry_count: number | null;
          completed_on: string | null;
          authorized: number | null;
          earned: number | null;
          invoiced: number | null;
          received: number | null;
          outstanding: number | null;
          last_invoice_on: string | null;
          unbilled: number | null;
          committed: number | null;
        };
        Relationships: [];
      };
      client_activity: {
        Row: {
          client_id: string | null;
          at: string | null;
          kind: string | null;
          title: string | null;
          detail: string | null;
          who: string | null;
          tab: string | null;
          ref_id: string | null;
        };
        Relationships: [];
      };
      client_job_history: {
        Row: {
          match_id: string | null;
          client_id: string | null;
          status: string | null;
          status_rank: number | null;
          applied_on: string | null;
          interview_on: string | null;
          follow_up_on: string | null;
          decided_on: string | null;
          outcome: string | null;
          notes: string | null;
          placement_id: string | null;
          created_at: string | null;
          updated_at: string | null;
          lead_id: string | null;
          title: string | null;
          wage_range: string | null;
          location: string | null;
          lead_status: string | null;
          employer_id: string | null;
          employer_name: string | null;
          contact_name: string | null;
          contact_phone: string | null;
          contact_email: string | null;
        };
        Relationships: [];
      };
      client_last_activity: {
        Row: {
          client_id: string | null;
          last_activity_at: string | null;
        };
        Relationships: [];
      };
      client_next_up: {
        Row: {
          client_id: string | null;
          at: string | null;
          kind: string | null;
          title: string | null;
        };
        Relationships: [];
      };
      client_paperwork: {
        Row: {
          client_id: string | null;
          auth_id: string | null;
          auth_number: string | null;
          service_type: string | null;
          template_id: string | null;
          usor: string | null;
          form_name: string | null;
          monthly: boolean | null;
          month: string | null;
          hours_logged: number | null;
          form_id: string | null;
          form_status: string | null;
          state: string | null;
        };
        Relationships: [];
      };
      contractor_statement_totals: {
        Row: {
          statement_id: string | null;
          staff_id: string | null;
          period_start: string | null;
          period_end: string | null;
          status: string | null;
          adjustment: number | null;
          adjustment_note: string | null;
          hours: number | null;
          unpriced_hours: number | null;
          rate_unit: string | null;
          period_rate: number | null;
          computed_amount: number | null;
          approved_hours: number | null;
          approved_amount: number | null;
          total_hours: number | null;
          total_amount: number | null;
        };
        Relationships: [];
      };
      contractor_year_totals: {
        Row: {
          staff_id: string | null;
          year: number | null;
          total_paid: number | null;
          payment_count: number | null;
          last_paid_on: string | null;
        };
        Relationships: [];
      };
      my_hours_summary: {
        Row: {
          staff_id: string | null;
          today_hours: number | null;
          period_hours: number | null;
          period_start: string | null;
          period_end: string | null;
        };
        Relationships: [];
      };
      my_tour_progress: {
        Row: {
          staff_id: string | null;
          hints_total: number | null;
          hints_seen: number | null;
        };
        Relationships: [];
      };
      staff_checklist: {
        Row: {
          staff_id: string | null;
          staff_name: string | null;
          staff_active: boolean | null;
          employment_type: string | null;
          task_id: string | null;
          phase: string | null;
          label: string | null;
          detail: string | null;
          auto_key: string | null;
          required: boolean | null;
          sort_order: number | null;
          auto_done: boolean | null;
          done_on: string | null;
          done_by: string | null;
          note: string | null;
        };
        Relationships: [];
      };
      work_session_totals: {
        Row: {
          staff_id: string | null;
          period_start: string | null;
          period_end: string | null;
          total_hours: number | null;
          session_count: number | null;
        };
        Relationships: [];
      };
      work_session_values: {
        Row: {
          id: string | null;
          staff_id: string | null;
          worked_on: string | null;
          hours: number | null;
          description: string | null;
          client_id: string | null;
          statement_id: string | null;
          pay_rate: number | null;
          rate_unit: string | null;
          amount: number | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      answer_reminder: {
        Args: { p_task_id: string | null; p_status: string | null; p_outcome: string | null };
        Returns: string;
      };
      can_see_restricted: {
        Args: { p_client_id: string | null };
        Returns: boolean;
      };
      current_staff_id: {
        Args: Record<string, never>;
        Returns: string;
      };
      current_staff_role: {
        Args: Record<string, never>;
        Returns: string;
      };
      delete_staff_pay: {
        Args: { p_id: string | null };
        Returns: string;
      };
      exclude_mail_thread: {
        Args: { p_conversation_id: string | null; p_reason: string | null };
        Returns: string;
      };
      fmt_hours: {
        Args: { n: number | null };
        Returns: string;
      };
      form_1099_candidates: {
        Args: { p_year: number | null };
        Returns: string;
      };
      generate_1099_run: {
        Args: { p_year: number | null };
        Returns: string;
      };
      generate_notifications: {
        Args: Record<string, never>;
        Returns: number;
      };
      get_contractor_tin: {
        Args: { p_staff_id: string | null };
        Returns: string;
      };
      get_employer_details: {
        Args: Record<string, never>;
        Returns: string;
      };
      get_microsoft_tokens: {
        Args: { p_staff_id: string | null };
        Returns: string;
      };
      get_microsoft_tokens_for_sync: {
        Args: { p_staff_id: string | null };
        Returns: string;
      };
      get_tax_form_sensitive: {
        Args: { p_form_id: string | null };
        Returns: string;
      };
      is_active_staff: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      is_admin: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      job_status_rank: {
        Args: { p_status: string | null };
        Returns: number;
      };
      log_mail_message: {
        Args: { p_client_id: string | null; p_counselor_id: string | null; p_message_id: string | null; p_conversation_id: string | null; p_subject: string | null; p_sent_at: string | null; p_direction: string | null; p_counterpart: string | null; p_web_link: string | null };
        Returns: boolean;
      };
      log_mail_message_for_sync: {
        Args: { p_staff_id: string | null; p_client_id: string | null; p_counselor_id: string | null; p_message_id: string | null; p_conversation_id: string | null; p_subject: string | null; p_sent_at: string | null; p_direction: string | null; p_counterpart: string | null; p_web_link: string | null };
        Returns: boolean;
      };
      log_shared_mail_message: {
        Args: { p_mailbox: string | null; p_client_id: string | null; p_counselor_id: string | null; p_message_id: string | null; p_conversation_id: string | null; p_subject: string | null; p_sent_at: string | null; p_direction: string | null; p_counterpart: string | null; p_web_link: string | null };
        Returns: boolean;
      };
      pay_rate_on: {
        Args: { p_staff_id: string | null; p_date: string | null };
        Returns: string;
      };
      period_end: {
        Args: { d: string | null };
        Returns: string;
      };
      period_start: {
        Args: { d: string | null };
        Returns: string;
      };
      practice_today: {
        Args: Record<string, never>;
        Returns: string;
      };
      record_1099_delivery: {
        Args: { p_recipient_id: string | null; p_method: string | null; p_delivered_on: string | null };
        Returns: string;
      };
      refresh_microsoft_tokens: {
        Args: { p_access: string | null; p_refresh: string | null; p_expires_at: string | null };
        Returns: string;
      };
      set_checklist_item: {
        Args: { p_staff_id: string | null; p_task_id: string | null; p_done: boolean | null; p_note: string | null };
        Returns: string;
      };
      set_contractor_tin: {
        Args: { p_staff_id: string | null; p_tin: string | null; p_tin_type: string | null };
        Returns: string;
      };
      set_e_delivery_consent: {
        Args: { p_consent: boolean | null };
        Returns: string;
      };
      set_employer_details: {
        Args: { p_legal_name: string | null; p_address: string | null; p_ein: string | null };
        Returns: string;
      };
      set_microsoft_error: {
        Args: { p_staff_id: string | null; p_error: string | null };
        Returns: string;
      };
      set_microsoft_tokens: {
        Args: { p_microsoft_user_id: string | null; p_email: string | null; p_display_name: string | null; p_scopes: string | null; p_access: string | null; p_refresh: string | null; p_expires_at: string | null };
        Returns: string;
      };
      set_microsoft_tokens_for_sync: {
        Args: { p_staff_id: string | null; p_access: string | null; p_refresh: string | null; p_expires_at: string | null };
        Returns: string;
      };
      set_staff_pay: {
        Args: { p_staff_id: string | null; p_rate: number | null; p_unit: string | null; p_effective_from: string | null; p_note: string | null };
        Returns: string;
      };
      set_statement_adjustment: {
        Args: { p_statement_id: string | null; p_amount: number | null; p_note: string | null };
        Returns: string;
      };
      sign_tax_form: {
        Args: { p_form_id: string | null; p_sensitive: Json | null; p_tin_last4: string | null; p_signer: string | null; p_ip: string | null };
        Returns: string;
      };
      staff_activity: {
        Args: { p_from: string | null; p_to: string | null };
        Returns: string;
      };
      timer_elapsed_hours: {
        Args: { p_started: string | null };
        Returns: number;
      };
    };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};

export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
export type Insert<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];
export type Update<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];
