/**
 * Generates lib/database.types.ts from the live schema.
 *
 *   node --env-file=.env.local scripts/gen-types.mjs
 *
 * The Supabase CLI's `gen types` wants a container runtime, which this machine
 * does not have. This reads information_schema over the same connection the
 * migrations use and emits the same shape supabase-js expects, so
 * createClient<Database>() gives typed rows everywhere.
 *
 * Re-run it after any migration that changes a table.
 */
import { writeFile } from "node:fs/promises";
import pg from "pg";

const TYPE_MAP = {
  uuid: "string",
  text: "string",
  varchar: "string",
  bpchar: "string",
  int2: "number",
  int4: "number",
  int8: "number",
  numeric: "number",
  float4: "number",
  float8: "number",
  bool: "boolean",
  date: "string",
  timestamp: "string",
  timestamptz: "string",
  time: "string",
  json: "Json",
  jsonb: "Json",
};

function tsType(udt) {
  if (udt.startsWith("_")) {
    const inner = TYPE_MAP[udt.slice(1)] ?? "string";
    return `${inner}[]`;
  }
  return TYPE_MAP[udt] ?? "string";
}

const client = new pg.Client({
  host: process.env.SUPABASE_DB_HOST,
  port: Number(process.env.SUPABASE_DB_PORT ?? 5432),
  user: process.env.SUPABASE_DB_USER ?? "postgres",
  password: process.env.SUPABASE_DB_PASSWORD,
  database: "postgres",
  ssl: { rejectUnauthorized: false },
});

await client.connect();

const { rows } = await client.query(`
  select c.table_name, c.column_name, c.udt_name, c.is_nullable,
         (c.column_default is not null) as has_default,
         c.is_generated
    from information_schema.columns c
    join information_schema.tables t
      on t.table_schema = c.table_schema and t.table_name = c.table_name
   where c.table_schema = 'public' and t.table_type = 'BASE TABLE'
   order by c.table_name, c.ordinal_position
`);

const { rows: fns } = await client.query(`
  select p.proname, pg_get_function_result(p.oid) as result
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public'
     and p.proname in ('current_staff_id','current_staff_role','is_active_staff','is_admin','can_see_restricted')
   order by p.proname
`);

await client.end();

const tables = new Map();
for (const r of rows) {
  if (!tables.has(r.table_name)) tables.set(r.table_name, []);
  tables.get(r.table_name).push(r);
}

const out = [];
out.push("// Generated by scripts/gen-types.mjs from the live schema. Do not edit by hand.");
out.push("// Re-run after any migration that changes a table.");
out.push("");
out.push("export type Json = string | number | boolean | null | { [key: string]: Json } | Json[];");
out.push("");
out.push("export type Database = {");
out.push("  public: {");
out.push("    Tables: {");

for (const [table, cols] of [...tables].sort((a, b) => a[0].localeCompare(b[0]))) {
  out.push(`      ${table}: {`);

  out.push("        Row: {");
  for (const c of cols) {
    const nullable = c.is_nullable === "YES" ? " | null" : "";
    out.push(`          ${c.column_name}: ${tsType(c.udt_name)}${nullable};`);
  }
  out.push("        };");

  out.push("        Insert: {");
  for (const c of cols) {
    const optional = c.has_default || c.is_nullable === "YES" || c.is_generated === "ALWAYS";
    const nullable = c.is_nullable === "YES" ? " | null" : "";
    out.push(`          ${c.column_name}${optional ? "?" : ""}: ${tsType(c.udt_name)}${nullable};`);
  }
  out.push("        };");

  out.push("        Update: {");
  for (const c of cols) {
    const nullable = c.is_nullable === "YES" ? " | null" : "";
    out.push(`          ${c.column_name}?: ${tsType(c.udt_name)}${nullable};`);
  }
  out.push("        };");

  // supabase-js requires this key to resolve its table generics; without it
  // every insert and update collapses to `never`.
  out.push("        Relationships: [];");

  out.push("      };");
}

out.push("    };");
out.push("    Views: { [_ in never]: never };");
out.push("    Functions: {");
for (const f of fns) {
  out.push(`      ${f.proname}: {`);
  out.push(`        Args: ${f.proname === "can_see_restricted" ? "{ p_client_id: string }" : "Record<string, never>"};`);
  out.push(`        Returns: ${f.result === "boolean" ? "boolean" : "string"};`);
  out.push("      };");
}
out.push("    };");
out.push("    Enums: { [_ in never]: never };");
out.push("    CompositeTypes: { [_ in never]: never };");
out.push("  };");
out.push("};");
out.push("");
out.push("export type Tables<T extends keyof Database[\"public\"][\"Tables\"]> =");
out.push("  Database[\"public\"][\"Tables\"][T][\"Row\"];");
out.push("export type Insert<T extends keyof Database[\"public\"][\"Tables\"]> =");
out.push("  Database[\"public\"][\"Tables\"][T][\"Insert\"];");
out.push("export type Update<T extends keyof Database[\"public\"][\"Tables\"]> =");
out.push("  Database[\"public\"][\"Tables\"][T][\"Update\"];");
out.push("");

await writeFile("lib/database.types.ts", out.join("\n"), "utf8");
console.log(`lib/database.types.ts — ${tables.size} tables, ${rows.length} columns, ${fns.length} functions`);
