-- ─────────────────────────────────────────────────────────────
-- 13.7 — the staff documents vault
--
-- The table has existed since 0015 and has been used for exactly one thing:
-- the tax PDFs the app generates. There has never been a way to put anything
-- else in it, so a signed handbook acknowledgement, a copy of a CPR card and
-- a background-check result all live in somebody's email.
--
-- Three changes make it a vault rather than a drawer the code writes to.
--
-- The categories become data, like every other list in this system that
-- turned out to need a new entry six months later.
--
-- A person may put their own documents in. Admin-only upload made sense when
-- the only writer was the tax-form generator; it is wrong for "send us your
-- CPR card", which is a thing the person does. Deleting stays Admin's,
-- because a personnel file somebody can quietly empty is not a personnel file.
--
-- And opening one is recorded, for the same reason opening a tax form is:
-- these are personnel records, and who read them is a fair question.
-- ─────────────────────────────────────────────────────────────

create table if not exists public.staff_file_categories (
  key         text primary key,
  label       text not null,
  detail      text not null default '',
  -- Generated by the app rather than uploaded by a person. Offered nowhere,
  -- because nobody uploads their own W-9 — they sign it here.
  system_only boolean not null default false,
  sort_order  integer not null default 100,
  active      boolean not null default true
);

alter table public.staff_file_categories enable row level security;

drop policy if exists staff_file_categories_read on public.staff_file_categories;
drop policy if exists staff_file_categories_write on public.staff_file_categories;

create policy staff_file_categories_read on public.staff_file_categories
  for select to authenticated using (public.is_active_staff());
create policy staff_file_categories_write on public.staff_file_categories
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

insert into public.staff_file_categories (key, label, detail, system_only, sort_order) values
  ('W-9',            'W-9',            'Signed in the app.', true, 10),
  ('W-8BEN',         'W-8BEN',         'Signed in the app.', true, 11),
  ('W-4',            'W-4',            'Signed in the app.', true, 12),
  ('I-9',            'I-9',            'Employment eligibility.', false, 20),
  ('Agreement',      'Agreement',      'Contract or engagement letter.', false, 30),
  ('Signed policy',  'Signed policy',  'Handbook, confidentiality, anything acknowledged in writing.', false, 40),
  ('Direct deposit', 'Direct deposit', 'Bank details form.', false, 50),
  ('Certificate',    'Certificate',    'ACRE, CPR, a course completion — the paper behind a credential.', false, 60),
  ('Licence',        'Licence',        'Driver''s licence, for anybody transporting clients.', false, 70),
  ('Insurance',      'Insurance',      'Proof of vehicle cover.', false, 80),
  ('Background check', 'Background check', 'BCI or FBI clearance result.', false, 90),
  ('Reference',      'Reference',      'A reference given or received.', false, 100),
  ('Other',          'Other',          'Say what it is in the note.', false, 999)
on conflict (key) do update set
  label = excluded.label, detail = excluded.detail,
  system_only = excluded.system_only, sort_order = excluded.sort_order;

-- The check constraint becomes a foreign key. Every value already in the
-- table is in the catalogue above, which is why this can be done in place.
alter table public.staff_files drop constraint if exists staff_files_category_check;

do $$
begin
  if not exists (
    select 1 from pg_constraint
     where conrelid = 'public.staff_files'::regclass and conname = 'staff_files_category_fkey'
  ) then
    alter table public.staff_files
      add constraint staff_files_category_fkey
      foreign key (category) references public.staff_file_categories(key);
  end if;
end $$;

-- ─────────────────────────────────────────────────────────────
-- Who may put something in
--
-- Your own, or anybody's if you are Admin. The storage policy has to say the
-- same thing as the table policy or the row lands and the file does not.
-- ─────────────────────────────────────────────────────────────
drop policy if exists staff_files_insert on public.staff_files;
create policy staff_files_insert on public.staff_files
  for insert to authenticated
  with check (
    (public.is_admin() or staff_id = public.current_staff_id())
    and uploaded_by is not distinct from public.current_staff_id()
  );

drop policy if exists "zion write staff files" on storage.objects;
create policy "zion write staff files" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'staff-files' and public.is_active_staff());

-- Deleting stays Admin's. A personnel file somebody can quietly empty is not
-- a personnel file — and the tax PDFs live in this bucket too.

-- ─────────────────────────────────────────────────────────────
-- Opening one is recorded
--
-- Same shape as note_tax_form_access from 0054: the file is in storage, so
-- the database cannot be the door, but it can refuse to say the download is
-- allowed without writing down that it said so.
-- ─────────────────────────────────────────────────────────────
alter table public.access_log drop constraint if exists access_log_subject_check;
alter table public.access_log add constraint access_log_subject_check
  check (subject in (
    'Client restricted details',
    'Client intake',
    'Contractor tax number',
    'Signed tax form',
    'Staff document'
  ));

create or replace function public.note_staff_file_access(p_file_id uuid)
returns boolean language plpgsql security definer set search_path = public as $$
declare
  v_owner uuid;
  v_name  text;
  v_cat   text;
begin
  select staff_id, filename, category into v_owner, v_name, v_cat
    from public.staff_files where id = p_file_id;

  if v_owner is null then return false; end if;

  -- Yours, or anybody's if you are Admin — the same rule the table applies,
  -- restated here because this function decides whether a link is minted.
  if not (public.is_admin() or v_owner = public.current_staff_id()) then
    perform public.log_access('Staff document', null, v_owner, 'refused');
    return false;
  end if;

  -- Reading your own file is not an event worth recording. The question this
  -- log answers is who else has been through somebody's personnel file, and
  -- filling it with a person opening their own would bury that.
  if v_owner <> public.current_staff_id() then
    perform public.log_access('Staff document', null, v_owner,
                              'opened ' || v_cat || ': ' || v_name);
  end if;

  return true;
end;
$$;

revoke execute on function public.note_staff_file_access(uuid) from public;
grant execute on function public.note_staff_file_access(uuid) to authenticated;

-- ─────────────────────────────────────────────────────────────
-- What is on file for each person
-- ─────────────────────────────────────────────────────────────
create or replace view public.staff_documents as
select f.id,
       f.staff_id,
       f.filename,
       f.category,
       coalesce(c.label, f.category)          as category_label,
       coalesce(c.system_only, false)         as system_generated,
       f.note,
       f.size_bytes,
       f.mime_type,
       f.storage_path,
       f.created_at,
       f.uploaded_by,
       u.name                                 as uploaded_by_name,
       -- Whether this document is standing behind a credential, so deleting
       -- it can say so rather than quietly leaving one unevidenced.
       exists (select 1 from public.staff_credentials sc where sc.file_id = f.id)
                                              as backs_a_credential
  from public.staff_files f
  left join public.staff_file_categories c on c.key = f.category
  left join public.staff s on s.id = f.staff_id
  left join public.staff u on u.id = f.uploaded_by;

alter view public.staff_documents set (security_invoker = true);
grant select on public.staff_documents to authenticated;

comment on view public.staff_documents is
  'Documents held for each member of staff, with who put them there and whether a credential is relying on one.';
